rewrote inventar text based
PM-Dungeon/PM-Lecture pull request #268
Opened 2022-03-07 13:44 UTC by AMatutat

Fixes #68 

- Umformulierung der Aufgabenstellung
- Ziel formuliert
- Implementierung von Item-Funktionen entfernt. Wird in die Item Aufgabe hinzugefügt.

2022-03-07 14:15 UTC, cagix requested changes
kleinkram

2022-03-07 14:15 UTC, cagix commented on markdown/assignments/pool_a/inventar_text_based/index.md
> +Um diese Aufgabe bearbeiten zu können, sollten Sie vorher die Aufgabe "Item" aus Pool C gelöst haben.
```suggestion
Um diese Aufgabe bearbeiten zu können, sollten Sie vorher die Aufgabe `["Item" aus Pool C]({{<ref "/assignments/pool_c/item" >}})`{=markdown} gelöst haben.
```

2022-03-07 14:15 UTC, cagix commented on markdown/assignments/pool_a/inventar_text_based/index.md
> +Um diese Aufgabe bearbeiten zu können, sollten Sie vorher die Aufgabe "Item" aus Pool C gelöst haben.
das müsste so gehen mit der verlinkung

2022-03-07 14:15 UTC, cagix commented on markdown/assignments/pool_a/inventar_text_based/index.md
> +In dieser Aufgabe sollen Sie ein textbasierter, also über die Konsole einseh- und steuerbares, Inventar implementieren.
```suggestion
In dieser Aufgabe sollen Sie ein textbasiertes, also über die Konsole einseh- und steuerbares, Inventar implementieren.
```

2022-03-08 05:14 UTC, cagix approved these changes

2022-03-08 05:32 UTC, cagix requested changes

2022-03-08 05:32 UTC, cagix commented on markdown/assignments/pool_a/inventar_text_based/index.md
> +Um diese Aufgabe bearbeiten zu können, sollten Sie vorher die Aufgabe `["Item" aus Pool C]({{<ref "/assignments/pool_c/item" >}})`{=markdown} gelöst haben.
```suggestion
Um diese Aufgabe bearbeiten zu können, sollten Sie vorher die Aufgabe `["Item" aus Pool C]({{< ref "/assignments/pool_c/item" >}})`{=markdown} gelöst haben.
```

2022-03-08 06:05 UTC, cagix requested changes

2022-03-08 06:05 UTC, cagix commented on markdown/assignments/pool_a/inventar_text_based/index.md
> +Im Inventar können Gegenstände gelagert, ausgerüstet oder verwendet werden.
```suggestion
Im Inventar können bestimmte Gegenstände gelagert, ausgerüstet oder verwendet werden.
```

2022-03-08 09:28 UTC, cagix approved these changes

2022-03-08 11:07 UTC, cagix approved these changes
A4

2022-03-30 10:21 UTC, AMatutat commented
@cagix Soll ich die Aufgaben hier mergen, wenn ich meine das passt?

2022-03-30 11:09 UTC, cagix commented
@AMatutat Nee, häng mir mal bitte um zum Merge (=> assign to cagix) ...

2022-03-30 16:05 UTC, cagix approved these changes

2022-03-30 16:05 UTC, merged