Aufgabe: Pool A: Charakterklassen
PM-Dungeon/PM-Lecture pull request #269
Opened 2022-03-07 14:05 UTC by AMatutat

Fixes #69

- Umformulierung der Aufgabenstellung
- Ziel formuliert
- Voraussetzung angegeben

2022-03-07 14:17 UTC, cagix requested changes
kleinkram

2022-03-07 14:17 UTC, cagix commented on markdown/assignments/pool_a/charakterklassen/index.md
> +In Rollenspielen ist es üblich, dass die Spielfigur einer bestimmen Klasse zugehörig ist. In dieser Aufgabe sollen Sie verschiedene Charakterklassen implementieren.
```suggestion
In Rollenspielen ist es üblich, dass die Spielfigur einer bestimmen Spiel-Klasse zugehörig ist. In dieser Aufgabe sollen Sie verschiedene Charakterklassen implementieren.
```

2022-03-07 14:17 UTC, cagix commented on markdown/assignments/pool_a/charakterklassen/index.md
> +Zu Beginn des Spiels soll der Spieler die Klasse Auswählen können (oder haben Sie eine bessere Idee?).
```suggestion
Zu Beginn des Spiels soll der Spieler die Klasse auswählen können (oder haben Sie eine bessere Idee?).
```

2022-03-08 05:17 UTC, cagix requested changes
- Der Text unter "Charakterklassen" wird als Fließtext erscheinen. Ist das so gewollt? Im Markdown habe ich das Gefühl, die Sätze sollten einzelne Absätze sein?

- Wissen die Studis, was "Charakterklassen" sind? Ich glaube, das müsste erklärt werden.

2022-03-08 05:17 UTC, cagix commented on markdown/assignments/pool_a/charakterklassen/index.md
> +Implementieren Sie nun die verschiedenen Charakterklassen im Sinne des OOP-Gedanken. Überlegen Sie auch, welche Pattern Sie ggf. verwenden können. Begründen Sie Ihre Entscheidungen schriftlich.
```suggestion
Implementieren Sie nun die verschiedenen Charakterklassen im Sinne des OOP-Gedankens. Überlegen Sie auch, welche Pattern Sie ggf. verwenden können. Begründen Sie Ihre Entscheidungen schriftlich.
```

2022-03-08 09:32 UTC, cagix submitted a review, later dismissed

2022-03-08 10:26 UTC, cagix requested changes

2022-03-08 10:26 UTC, cagix commented on markdown/assignments/pool_a/charakterklassen/index.md
> +In Rollenspielen gibt die Charakterklasse an, welche Werte (Anzahl der Lebenspunkte, Kampfschaden, `[Manapunkte]({{<ref "https://de.wikipedia.org/wiki/Mana_(Spiele)" >}})`{=markdown} etc.) die Spielf
```suggestion
In Rollenspielen gibt die Charakterklasse an, welche Werte (Anzahl der Lebenspunkte, Kampfschaden, [Mana-Punkte](https://de.wikipedia.org/wiki/Mana_(Spiele)) etc.) die Spielfigur hat, welche Waffen sie verwenden und welche Fähigkeiten sie erlernen kann. Typische Charakterklassen sind Krieger, Zauberer oder Schurke.
```

2022-03-08 11:08 UTC, cagix approved these changes
A6

@AMatutat A5 fehlt noch?

2022-03-08 11:14 UTC, AMatutat commented
> @AMatutat A5 fehlt noch?

A5 ist Crafting, da passte der Wert ^^

2022-03-08 11:23 UTC, cagix commented
> > @AMatutat A5 fehlt noch?
> 
> A5 ist Crafting, da passte der Wert ^^

ah, ok. sorry, hatte ich nicht mehr auf dem schirm gehabt ...

2022-03-08 11:23 UTC, cagix submitted a review, later dismissed
A6

2022-03-30 16:11 UTC, merged