Aufgabe: Pool A: Fallen
PM-Dungeon/PM-Lecture pull request #273
Opened 2022-03-07 14:32 UTC by AMatutat

Fixes #272

- Umformulierung der Aufgabenstellung
- Ziel formuliert

2022-03-08 05:35 UTC, cagix requested changes
Ich verstehe die Intention, aber ich glaube, das Wort "fies" sollten wir nicht auf dem Aufgabenblatt verwenden ...

2022-03-08 05:35 UTC, cagix commented on markdown/assignments/pool_a/fallen/index.md
> +In dieser Aufgaben sollen Sie fiese Fallen implementieren, die das vorranschreiten im Dungeon schwieriger machen.
```suggestion
In dieser Aufgaben sollen Sie Fallen implementieren, die das Vorranschreiten im Dungeon schwieriger machen.
```

2022-03-08 09:27 UTC, cagix submitted a review, later dismissed

2022-03-08 10:06 UTC, cagix commented
@AMatutat #271, #273 und #275 haben alle als `weight` den Wert "5". 

Soll das so, d.h. sind die Aufgaben gleichwertig und Hugo soll die untereinander alphabetisch sortieren? 

Oder sollten wir die einfach fortlaufend durchnummerieren? Vielleicht in der Reihenfolge, in der die Dinger sinnvollerweise bearbeitet werden sollten?

2022-03-08 10:17 UTC, AMatutat commented
> https://github.com/PM-Dungeon/PM-Lecture/pull/271, https://github.com/PM-Dungeon/PM-Lecture/pull/273 und https://github.com/PM-Dungeon/PM-Lecture/pull/275 haben alle als weight den Wert "5".

Habe ich mir noch keine aktiven Gedanken drüber gemacht. Eigentlich ist die Reihenfolge egal. 

> Vielleicht in der Reihenfolge, in der die Dinger sinnvollerweise bearbeitet werden sollten?

Könnte man versuchen. Zumindest sollten man Aufgaben die andere Aufgaben voraussetzten nicht über diesen listen.

2022-03-08 10:21 UTC, cagix commented
> > #271, #273 und #275 haben alle als weight den Wert "5".
> 
> Habe ich mir noch keine aktiven Gedanken drüber gemacht. Eigentlich ist die Reihenfolge egal.

Naja, wenn wir kein "weight" definieren oder überlappende Werte setzen, dann sortiert Hugo die alphabetisch. Ist vielleicht auch irgendwie wieder komisch.

 
> > Vielleicht in der Reihenfolge, in der die Dinger sinnvollerweise bearbeitet werden sollten?
> 
> Könnte man versuchen. Zumindest sollten man Aufgaben die andere Aufgaben voraussetzten nicht über diesen listen.

Sowas in der Art. Die Frage ist nur: Hast Du da schon einen Überblick, dass Du das jetzt schon sortieren kannst? Ansonsten müssten wir uns ein Ticket dafür aufmachen und ich sollte die überlappenden PRs noch nicht approven.

2022-03-08 10:27 UTC, AMatutat commented
> Sowas in der Art. Die Frage ist nur: Hast Du da schon einen Überblick, dass Du das jetzt schon sortieren kannst? Ansonsten müssten wir uns ein Ticket dafür aufmachen und ich sollte die überlappenden PRs noch nicht approven.

Ich hab da eigentlich einen ganz guten Überblick. Ich passe das gleich an.

2022-03-08 11:06 UTC, cagix submitted a review, later dismissed
A3

2022-03-30 16:02 UTC, cagix approved these changes

2022-03-30 16:03 UTC, merged