Aufgabe: Project
PM-Dungeon/PM-Lecture pull request #279
Opened 2022-03-08 14:56 UTC by AMatutat

Ich muss noch die Daten und verantwortliche eintragen. 

@cagix Unsere 50% Regel für die Projekte funktioniert irgendwie nicht so richtig. Habs mal auf 15-Punkte runtergedreht (als Vorschlag).

2022-03-08 15:13 UTC, cagix requested changes
Sieht doch schon gut aus.

Wir sollten das "Vorher-Absprechen-und-Genehmigen" am Freitag nochmal diskutieren. Vermutlich macht es Sinn, wenn die Studis in der Woche vor dem Projekt-Start im Praktikum jeweils ihre Idee Jonas und/oder Dir vorstellen.

2022-03-08 15:13 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +Ein Projekt hat eine Laufzeit von 2 Wochen. In dieser Zeit bearbeiten Sie nur die Aufgaben aus dem pool_k und Ihr Projekt. Andere Pool-Aufgaben müssen Sie nicht parallel bearbeiten.
```suggestion
Ein Projekt hat eine Laufzeit von **zwei** Wochen. In dieser Zeit bearbeiten Sie nur die Aufgaben aus dem `[Pool K]({{<ref "/assignments/pool_k" >}})`{=markdown} und Ihr Projekt. Andere Pool-Aufgaben müssen Sie nicht parallel bearbeiten.
```

2022-03-08 15:13 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +weight: 1
Das brauchen wir nicht, wenn es nur die eine Seite gibt. (Aber es schadet auch nicht.)

2022-03-08 15:13 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +points: 20
Wolltest Du das nicht auf 15 Punkte runterdrehen? Zumindest hatte ich https://github.com/PM-Dungeon/PM-Lecture/pull/279#issue-1162757054 so verstanden?

2022-03-08 15:13 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +Um den pool_p erfolgreich zu absolvieren, müssen sie mindestens 15-Punkte holen.
```suggestion
Um den `[Pool P]({{<ref "/assignments/pool_p" >}})`{=markdown} erfolgreich zu absolvieren, müssen sie hier **mindestens 15 Punkte** erreichen.
```

2022-03-08 15:13 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +Bei der Punktevergabe kommt es nicht nur darauf an, ob Sie Ihr Ziel erreicht haben, sondern auch darauf, ob Sie die Ihnen bekannten Maßnahmen zur Einhaltung der Softwarequalität genutzt haben (Testfä
```suggestion
Bei der Punktevergabe kommt es nicht nur darauf an, ob Sie Ihr Ziel erreicht haben, sondern auch darauf, ob Sie die Ihnen bekannten Maßnahmen zur Einhaltung der Softwarequalität genutzt haben (Testfälle, Logging, Code-Style). Auch die Qualität Ihrer schriftlichen Ausarbeitung fließt in die Punktevergabe mit ein.
```

2022-03-08 15:13 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +Sie können die Projekte erst ab dem xx.xx (nach dem ersten E-Assesment) starten.
```suggestion
Sie können die Projekte erst ab Woche 9 (d.h. ab KW22, also in der Woche nach dem ersten E-Assessment) starten.
```

2022-03-10 10:01 UTC, AMatutat commented on markdown/assignments/pool_p/projekt/index.md
> +points: 20
Ne wollte ich nicht. Ich wollte/habe die besteh Grenze von pool_p von 20 auf 15 verschoben.

2022-03-10 11:02 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +points: 20
ah, ok. habe ich wohl durcheinander gebracht.

2022-03-11 08:05 UTC, cagix requested changes
Ich habe das Gefühl, hier sind bereits besprochene Änderungen verloren gegangen?

2022-03-11 08:05 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +Ein Projekt hat eine Laufzeit von **zwei** Wochen. In dieser Zeit bearbeiten Sie nur die Aufgaben aus dem `[Pool K]({{<ref "/assignments/pool_k" >}})`{=markdown} und Ihr Projekt. Andere Pool-Aufgaben
```suggestion
Ein Projekt hat eine Laufzeit von **zwei** Wochen. In dieser Zeit bearbeiten Sie nur die Aufgaben aus dem `[Pool K]({{< ref "/assignments/pool_k" >}})`{=markdown} und Ihr Projekt. Andere Pool-Aufgaben müssen Sie nicht parallel bearbeiten.
```

2022-03-11 08:05 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +Um den `[Pool P]({{<ref "/assignments/pool_p" >}})`{=markdown} erfolgreich zu absolvieren, müssen sie hier **mindestens 15 Punkte** erreichen.
```suggestion
Um den `[Pool P]({{< ref "/assignments/pool_p" >}})`{=markdown} erfolgreich zu absolvieren, müssen sie hier **mindestens 15 Punkte** erreichen.
```

2022-03-11 08:05 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +Sie müssen das Projekt vorher mit ??? absprechen. Bereiten Sie dafür ein kurzes Konzept vor und erklären Sie, was Sie machen möchten, wie Sie dabei vorgehen wollen und welche Probleme/Fragen es gibt.
- Was bedeutet "kurzes Konzept"? Wir sollten eine Seitenzahl angeben, beispielsweise 1..3 Seiten, Format PDF.
- Was bedeutet "melden Sie sich frühzeitig"? Wie früh ist früh genug? Bei wem sollen sie sich melden?

2022-03-11 08:05 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +Bei der Punktevergabe kommt es nicht nur darauf an, ob Sie Ihr Ziel erreicht haben, sondern auch darauf, ob Sie die Ihnen bekannten Maßnahmen zur Einhaltung der Softwarequalität genutzt haben (Testfä
- zur "schriftlichen Ausarbeitung" fehlen noch die Kriterien: Was soll aufgeschrieben werden, in welchem Umfang ...

2022-03-11 16:10 UTC, AMatutat commented
Ach mist jetzt haben wir das garnicht besprochen.

2022-03-11 16:16 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +Ein Projekt hat eine Laufzeit von **zwei** Wochen. In dieser Zeit bearbeiten Sie nur die Aufgaben aus dem `[Pool K]({{< ref "/assignments/pool_k" >}})`{=markdown} und Ihr Projekt. Andere Pool-Aufgabe
```suggestion
Ein Projekt hat eine Laufzeit von **zwei** Wochen. In dieser Zeit bearbeiten Sie nur die Aufgaben aus dem `[Pool K]({{< ref "/assignments/pool_k" >}})`{=markdown} und Ihr Projekt. Andere Pool-Aufgaben können Sie nicht parallel bearbeiten.
```

2022-03-11 18:04 UTC, cagix commented on markdown/assignments/pool_p/projekt/index.md
> +Sie müssen das Projekt vorher mit ??? absprechen. Bereiten Sie dafür ein kurzes Konzept vor und erklären Sie, was Sie machen möchten, wie Sie dabei vorgehen wollen und welche Probleme/Fragen es gibt.
siehe https://github.com/PM-Dungeon/PM-Lecture/issues/89#issue-1138610219

2022-03-21 18:41 UTC, cagix requested changes
sieht doch schon gut aus. fehlen "nur" noch die kriterien ...

2022-03-21 18:41 UTC, cagix commented on markdown/assignments/pool_p/_index.md
> +Sie können insgesamt zwei Projekte durchführen, müssen aber mindestens eines durchführen.
```suggestion
Sie können im Semester insgesamt zwei Projekte durchführen, müssen aber mindestens eines erfolgreich bearbeiten.
```

2022-03-21 18:41 UTC, cagix commented on markdown/assignments/pool_p/_index.md
> +Sie müssen das Projekt vorher mit Jonas Posselt absprechen. Bereiten Sie dafür ein kurzes Konzept vor und erklären Sie, was Sie machen möchten, wie Sie dabei vorgehen wollen und welche Probleme/Frage
```suggestion
Sie müssen das Projekt vorab mit Jonas Posselt absprechen. Bereiten Sie dafür ein kurzes Konzept vor und erklären Sie, was Sie machen möchten, wie Sie dabei vorgehen wollen und welche Probleme/Fragen es gibt. Melden Sie sich bitte spätestens eine Woche bevor Sie das Projekt starten wollen im Praktikum bei Jonas.
```

2022-03-21 18:41 UTC, cagix commented on markdown/assignments/pool_p/_index.md
> +Nach der ersten Woche müssen Sie ein schriftliches Feinkonzept und einen ersten Grobentwurf der Implementierung vorstellen. Für diesen Teil können Sie bis zu 10 Punkte erhalten.
```suggestion
Nach der ersten Woche müssen Sie ein schriftliches Feinkonzept und einen ersten Grobentwurf der Implementierung im Praktikum vorstellen. Für diesen Teil können Sie bis zu 10 Punkte erhalten.
```

2022-03-21 18:41 UTC, cagix commented on markdown/assignments/pool_p/_index.md
> +Nach der zweiten Woche stellen Sie das Ergebnis vor. Dies beinhaltet die fertiggestellte Dokumentation (**TODO PUNKTE**), das Lerntagebuch (**TODO PUNKTE**) und die lauffähige Software (**TODO PUNKTE
```suggestion
In der zweiten Woche stellen Sie das Ergebnis im Praktikum vor. Dies beinhaltet die fertiggestellte Dokumentation (**TODO PUNKTE**), das Lerntagebuch (**TODO PUNKTE**) und die lauffähige Software (**TODO PUNKTE**). Für diesen Teil können Sie bis zu 10 Punkte erhalten. Beachten Sie dieselben Kriterien wie bei den anderen Abgaben (Logging, Dokumentation, Testfälle, Codestile etc.). 
```

2022-03-28 13:39 UTC, AMatutat commented
@cagix das hier ist jetzt eigentlich outdated, oder?

2022-03-28 13:45 UTC, cagix commented
ja

2022-03-28 13:50 UTC, closed without merging