rewrote magie
PM-Dungeon/PM-Lecture pull request #300
Opened 2022-03-10 10:45 UTC by AMatutat

Fixes #75

2022-03-11 08:51 UTC, cagix requested changes
Hier könnten die Studis ein wenig auf dem Schlauch stehen. 

Sollten wir noch ergänzen, dass man Zaubersprüche im Dungeon finden kann und nur nach dem Aufsammeln nutzen kann? 

Sollten wir ergänzen, dass Zaubersprüche nur auf den Helden und seine Ausrüstung wirken oder soll das auch auf Gegner wirken können. Aber das wäre dann ja "Kampf" und wird in Zeile 18 eigentlich ausgeschlossen.

2022-03-11 08:51 UTC, cagix commented on markdown/assignments/pool_b/magie/index.md
>  Implementieren Sie ein Magie-System. Der Spieler soll in der Lage sein verschiedene Zauber zu verwenden.
```suggestion
Implementieren Sie ein Magie-System. Der Spieler soll in der Lage sein, verschiedene Zauber zu verwenden.
```

2022-03-11 08:51 UTC, cagix commented on markdown/assignments/pool_b/magie/index.md
>  Beachten Sie dabei, das es sich nicht um Zauber handelt die als "Fernkampf" bezeichnet werden können (also keine Feuerbälle).
```suggestion
Beachten Sie dabei, dass es sich nicht um Zauber handelt, die als "Fernkampf" bezeichnet werden können (also keine Feuerbälle o.ä.).
```

2022-03-11 08:51 UTC, cagix commented on markdown/assignments/pool_b/magie/index.md
>  Überlegen Sie sich zwei verschiedene Zaubersprüche wie Gedankenkontrolle oder Telekinese.
```suggestion
Überlegen Sie sich zwei verschiedene Zaubersprüche wie Gedankenkontrolle oder Telekinese oder Upgrade von Waffen/Rüstungen.
```

2022-03-11 10:22 UTC, AMatutat commented
> Sollten wir noch ergänzen, dass man Zaubersprüche im Dungeon finden kann und nur nach dem Aufsammeln nutzen kann?

Würde ich freistellen. Kann man so machen, muss man nicht. Wenn du sie finden kannst, geht es eher in Richtung Item und Funktion von Items. 

> Sollten wir ergänzen, dass Zaubersprüche nur auf den Helden und seine Ausrüstung wirken oder soll das auch auf Gegner wirken können. Aber das wäre dann ja "Kampf" und wird in Zeile 18 eigentlich ausgeschlossen.

Kampf wäre für mich alles, was Schaden macht. Ein Zauber zum Kontrollieren von Monstern wäre für mich kein Kampf-Zauber. Soll ich das nochmal klarer machen?

2022-03-11 10:24 UTC, cagix commented
> > Sollten wir noch ergänzen, dass man Zaubersprüche im Dungeon finden kann und nur nach dem Aufsammeln nutzen kann?
> 
> Würde ich freistellen. Kann man so machen, muss man nicht. Wenn du sie finden kannst, geht es eher in Richtung Item und Funktion von Items.

Das war für mich eine eher praktische Frage: Wie komme ich denn an Zaubersprüche dran? Insofern dachte ich an Zaubersprüche als spezielle Items.


 
> > Sollten wir ergänzen, dass Zaubersprüche nur auf den Helden und seine Ausrüstung wirken oder soll das auch auf Gegner wirken können. Aber das wäre dann ja "Kampf" und wird in Zeile 18 eigentlich ausgeschlossen.
> 
> Kampf wäre für mich alles, was Schaden macht. Ein Zauber zum Kontrollieren von Monstern wäre für mich kein Kampf-Zauber. Soll ich das nochmal klarer machen?

Ja, die Erklärung macht Sinn, eine Ergänzung wäre gut.

2022-03-11 13:30 UTC, cagix submitted a review, later dismissed
B5

2022-03-30 16:32 UTC, cagix commented on markdown/assignments/pool_b/magie/index.md
> +
```suggestion
```

2022-03-30 16:33 UTC, cagix approved these changes

2022-03-30 16:33 UTC, merged