Aufgabe: Pool C: Inventar UI
PM-Dungeon/PM-Lecture pull request #311
Opened 2022-03-10 12:15 UTC by AMatutat

Fixes #82

2022-03-11 09:22 UTC, cagix requested changes
Das Handling sollte etwas präzisiert werden. Schau mal, ob Dir mein Vorschlag gefällt.

2022-03-11 09:22 UTC, cagix commented on markdown/assignments/pool_c/inventar_ui/index.md
> +Implementieren Sie eine grafische Oberfläche für das Inventar. Stellen Sie die verschiedenen Items grafisch dar und erlauben Sie es, Items mithilfe der Maus zu verwenden oder fallen zu lassen.
```suggestion
Implementieren Sie eine grafische Oberfläche für das Inventar. Ergänzen Sie passende Befehle, so dass das Inventar ein- und auch wieder ausgeblendet werden kann. Das Ein- und Ausblenden des Inventars soll keinen Spielzug kosten.

Stellen Sie die verschiedenen Items grafisch dar und erlauben Sie es, Items mithilfe der Maus zu verwenden oder fallen zu lassen.
```

2022-03-11 10:35 UTC, cagix approved these changes
C5

2022-03-11 10:36 UTC, AMatutat commented
@cagix ich hab den Hinweis auf den Spielzug entfernt. Unser Dungeon ist Framebased und daher gibt es keine richtigen Spielzüge. Könnte zu Verwirrung kommen.

2022-03-11 10:38 UTC, cagix commented
> @cagix ich hab den Hinweis auf den Spielzug entfernt. Unser Dungeon ist Framebased und daher gibt es keine richtigen Spielzüge. Könnte zu Verwirrung kommen.

@AMatutat Framebased? Ich dachte, wir haben eine Game-Loop, in der Aktionen gemacht werden. Typischerweise wird dabei die nächste Position und auch die nächste Aktion berechnet/durchgeführt. Ich fände es doof, wenn das Handling vom Inventar dabei quasi einen Spielzug (Durchlauf der Game-Loop) kosten würde. Insofern sollte das schon den Studis als Idee mitgegeben werden aus meiner Sicht.

2022-03-11 10:44 UTC, AMatutat commented
Rundenbasiert/Zugbasiert:
Die Game-Loop geht jeden Akteur im Dungeon nacheinander ab und wartet bis dieser eine Aktion tätigt. Machst du keine Aktion, geht es nicht weiter und alle müssen auf dich warten. Wie in typischen Brettspielen.

Framebased/Echtzeit:
Die Game-Loop läuft jeden Akteur im Dungeon (nahe zu) zeitgleich ab und prüft, ob dieser eine Aktion durchführen möchte oder nicht. Willst du keine Aktion durchführen, muss niemand auf dich warten. Ein wenig wie beim Fußball, der Torwart darf den Ball werfen egal ob der Stürmer sich bewegt oder nicht.

2022-03-11 10:52 UTC, cagix commented
> Rundenbasiert/Zugbasiert: Die Game-Loop geht jeden Akteur im Dungeon nacheinander ab und wartet bis dieser eine Aktion tätigt. Machst du keine Aktion, geht es nicht weiter und alle müssen auf dich warten. Wie in typischen Brettspielen.

Das würde ich so nicht unterschreiben. Auch hier geht die Game-Loop mit dem Observer-Pattern jeden Akteur (nahezu zeitgleich: nacheinander) durch und fragt ab, ob es hier eine Änderung geben soll. Der Unterschied zu Framebased ist imho, dass die Game-Loop nicht unabhängig von den Akteuren läuft, sondern nur durch eine Eingabe des Spielers getriggert wird. Bei Framebased ist der Trigger die Uhr.

> 
> Framebased/Echtzeit: Die Game-Loop läuft jeden Akteur im Dungeon (nahe zu) zeitgleich ab und prüft, ob dieser eine Aktion durchführen möchte oder nicht. Willst du keine Aktion durchführen, muss niemand auf dich warten. Ein wenig wie beim Fußball, der Torwart darf den Ball werfen egal ob der Stürmer sich bewegt oder nicht.

Hmmm, ich sehe, dass ich beides vermischt habe. Ich glaube, das sollten wir irgendwo nochmal klar und deutlich hinschreiben. 

Dennoch: Sollten wir einen Hinweis auf das Verhalten beim Ansehen des Inventars einbauen? Sonst stirbst Du, wenn Du Dir Dein Inventar ansiehst ...

2022-03-11 10:56 UTC, AMatutat commented
> Dennoch: Sollten wir einen Hinweis auf das Verhalten beim Ansehen des Inventars einbauen? Sonst stirbst Du, wenn Du Dir Dein Inventar ansiehst ...

Ich finde, wir können das offen lassen. Wer möchte, kann eine Pause-Funktion implementieren und wer nicht, der nicht. Ich persönlich finde es in solchen Spielen schon besser, wenn die Zeit im Inventar nicht stillsteht, aber das ist halt Geschmackssache.

2022-03-11 10:57 UTC, cagix requested changes

2022-03-11 10:57 UTC, cagix commented on markdown/assignments/pool_c/inventar_ui/index.md
> +Stellen Sie die verschiedenen Items grafisch dar und erlauben Sie es, Items mithilfe der Maus zu verwenden oder fallen zu lassen.
```suggestion
Stellen Sie die verschiedenen Items grafisch dar und erlauben Sie es, Items mithilfe der Maus zu verwenden oder fallen zu lassen.

Bedenken Sie, dass die Game-Loop zeitgesteuert weiterläuft und entsprechend die Gegner und NPCs im Prinzip auch angreifen können, wenn der Spieler sein Inventar anschaut. Eventuell möchten Sie einen Mechanismus implementieren, so dass die Gegner keinen Zug machen, so lange das Inventar angezeigt wird und der Held handlungsunfähig ist.
```

2022-03-11 10:58 UTC, cagix commented
> > Dennoch: Sollten wir einen Hinweis auf das Verhalten beim Ansehen des Inventars einbauen? Sonst stirbst Du, wenn Du Dir Dein Inventar ansiehst ...
> 
> Ich finde, wir können das offen lassen. Wer möchte, kann eine Pause-Funktion implementieren und wer nicht, der nicht. Ich persönlich finde es in solchen Spielen schon besser, wenn die Zeit im Inventar nicht stillsteht, aber das ist halt Geschmackssache.

Offen lassen: Ja. Ich würde dennoch drauf hinweisen wollen (siehe Vorschlag).

2022-03-11 11:17 UTC, AMatutat commented
Find ich gut.

2022-03-11 11:19 UTC, cagix approved these changes
C5

2022-03-30 17:08 UTC, cagix approved these changes

2022-03-30 17:08 UTC, merged