Aufgabe: Pool C: NPC
PM-Dungeon/PM-Lecture pull request #312
Opened 2022-03-10 12:44 UTC by AMatutat

Fixes #85

2022-03-11 09:26 UTC, cagix requested changes
Ich würde lieber auf Wiki verlinken. Aber letztlich musst Du hier entscheiden.

Eine dumme Frage: Sind Monster nicht auch NPC? Die sind ja auch nicht vom Spieler kontrolliert ... Hier brauchen wir imho eine gute Abgrenzung in der Formulierung.

2022-03-11 09:26 UTC, cagix commented on markdown/assignments/pool_c/npc/index.md
> +In dieser Aufgabe implementieren Sie [NPCs(Non-Player-Character)](https://usk.de/alle-lexikonbegriffe/non-player-character/#:~:text=NPC%20oder%20Non%2DPlayer%2DCharacter,hin%20zu%20tragende%20Rollen%
```suggestion
In dieser Aufgabe implementieren Sie [NPCs (Non-Player-Character)](https://en.wikipedia.org/wiki/Non-player_character).
```

2022-03-11 09:26 UTC, cagix commented on markdown/assignments/pool_c/npc/index.md
> +*Anmerkung: Die Aufgabe lässt sich hervorragend mit der Aufgabe `["Shop"]({{< ref "/assignments/pool_c/shop" >}})`{=markdown} und `["Dialogsystem"]({{< ref "/assignments/pool_c/dialogsystem" >}})`{=m
```suggestion
*Anmerkung*: Die Aufgabe lässt sich hervorragend mit der Aufgabe `["Shop"]({{< ref "/assignments/pool_c/shop" >}})`{=markdown} und `["Dialogsystem"]({{< ref "/assignments/pool_c/dialogsystem" >}})`{=markdown} kombinieren.
```

2022-03-11 11:42 UTC, AMatutat commented
> Eine dumme Frage: Sind Monster nicht auch NPC? Die sind ja auch nicht vom Spieler kontrolliert ... Hier brauchen wir imho eine gute Abgrenzung in der Formulierung.

Ja, das stimmt. Monster sind auch NPCs. 
Darum habe ich auch das geschrieben: 
> Anders als Monster sollen diese NPCs den Spieler **nicht** angreifen.

Die NPCs sind auch nur eine no-brainer Vorbereitungsaufgabe für Quests, Dialoge, Shops.

2022-03-11 12:11 UTC, cagix commented
> > Eine dumme Frage: Sind Monster nicht auch NPC? Die sind ja auch nicht vom Spieler kontrolliert ... Hier brauchen wir imho eine gute Abgrenzung in der Formulierung.
> 
> 
> 
> Ja, das stimmt. Monster sind auch NPCs. 
> 
> Darum habe ich auch das geschrieben: 
> 
> > Anders als Monster sollen diese NPCs den Spieler **nicht** angreifen.

Verstehe, sollten wir die Aufgabe dann irgendwie umbenennen (nur Titel und im Text)? Irgendwie als "Nichtangreifende NPC" oder so? 

Die Studis stolpern vermutlich auch drüber und überlesen den Hinweis mit "anders als monster..."?


> 
> Die NPCs sind auch nur eine no-brainer Vorbereitungsaufgabe für Quests, Dialoge, Shops. 

Der zweite Teil dieses Satzes könnte noch mit in den Text :)

2022-03-11 12:17 UTC, AMatutat commented
> Der zweite Teil dieses Satzes könnte noch mit in den Text :)

Reicht 

> *Anmerkung*: Die Aufgabe lässt sich hervorragend mit der Aufgabe `["Shop"]({{< ref "/assignments/pool_c/shop" >}})`{=markdown} und `["Dialogsystem"]({{< ref "/assignments/pool_c/dialogsystem" >}})`{=markdown} kombinieren.


das nicht?


NPCs. sind jetzt freundlich.

2022-03-11 13:39 UTC, cagix requested changes
ein letzter Formulierungsvorschlag ...

2022-03-11 13:39 UTC, cagix commented on markdown/assignments/pool_c/npc/index.md
> +*Anmerkung*: Die Aufgabe lässt sich hervorragend mit der Aufgabe `["Shop"]({{< ref "/assignments/pool_c/shop" >}})`{=markdown} und `["Dialogsystem"]({{< ref "/assignments/pool_c/dialogsystem" >}})`{=
```suggestion
*Anmerkung*: Diese Aufgabe lässt sich hervorragend mit den Aufgaben `["Shop"]({{< ref "/assignments/pool_c/shop" >}})`{=markdown} und `["Dialogsystem"]({{< ref "/assignments/pool_c/dialogsystem" >}})`{=markdown} kombinieren.
```

2022-03-11 13:42 UTC, cagix requested changes

2022-03-11 13:42 UTC, cagix commented on markdown/assignments/pool_c/npc/index.md
> +*Anmerkung*: Diese Aufgabe ist als Vorbereitung für andere Aufgaben gedacht und lässt sich hervorragend mit der Aufgabe `["Shop"]({{< ref "/assignments/pool_c/shop" >}})`{=markdown} und `["Dialogsyst
```suggestion
*Anmerkung*: Diese Aufgabe ist als Vorbereitung für andere Aufgaben gedacht und lässt sich hervorragend mit den Aufgaben `["Shop"]({{< ref "/assignments/pool_c/shop" >}})`{=markdown} und `["Dialogsystem"]({{< ref "/assignments/pool_c/dialogsystem" >}})`{=markdown} kombinieren.
```

2022-03-11 13:43 UTC, cagix commented on markdown/assignments/pool_c/npc/index.md
> +*Anmerkung*: Diese Aufgabe ist als Vorbereitung für andere Aufgaben gedacht und lässt sich hervorragend mit der Aufgabe `["Shop"]({{< ref "/assignments/pool_c/shop" >}})`{=markdown} und `["Dialogsyst
das mit der Vorbereitung gefällt mir 👍

2022-03-11 13:46 UTC, cagix submitted a review, later dismissed
C6

2022-03-30 17:09 UTC, cagix commented on markdown/assignments/pool_c/npc/index.md
> +In dieser Aufgabe implementieren Sie [freundliche NPCs (Non-Player-Character)](https://en.wikipedia.org/wiki/Non-player_character).
```suggestion
In dieser Aufgabe implementieren Sie freundliche [NPCs (_Non-Player-Character_)](https://en.wikipedia.org/wiki/Non-player_character).
```

2022-03-30 17:12 UTC, cagix approved these changes

2022-03-30 17:12 UTC, merged